### PR TITLE
Accept that parsing downcases the scheme part, allow Addressable 2.6

### LINKED ISSUE #132: Update addressable to 2.6
We're limiting to 2.5 currently:

https://github.com/twingly/twingly-url/blob/c2218e98ff0892e63adc483f4cf1c06e4f01f3ae/twingly-url.gemspec#L17

Did a quick test, but we need to either change our specs or look into why the protocol is updated:

```
Failures:

  1) Twingly::URL.parse when given valid urls does not ruin the url "hTTP://blog.twingly.com/"
     Failure/Error: expect(described_class.parse(valid_url).to_s).to eq(valid_url)

       expected: "hTTP://blog.twingly.com/"
            got: "http://blog.twingly.com/"

       (compared using ==)
     # ./spec/lib/twingly/url_spec.rb:124:in `block (5 levels) in <top (required)>'
```

### PR DESCRIPTION
**Pull request by dentarg**
This is the situation since Addressable 2.6: https://github.com/sporkmonger/addressable/pull/281

Close #132

### CODE REVIEW

**Comment by dentarg** [comment]
Does this require another major bump? 😬 

Something changed, but I don't think it is particular breaking.

File: spec/lib/twingly/url_spec.rb [hunk 1]
```diff
@@ -135,6 +134,13 @@ def leading_and_trailing_whitespace
       end
     end
 
+    context "downcases the protocol" do
```
Comment (walro) [inline spec/lib/twingly/url_spec.rb]: "downcases the protocol" sounds more like an "it" than an "context". I'd go with something like:

```ruby
context "when given an URL with uppercase protocol" do
  it "downcases the protocol" do
    ...
```

Comment (dentarg) [reply spec/lib/twingly/url_spec.rb]: I just copied an existing spec! 🙈

Comment (dentarg) [reply spec/lib/twingly/url_spec.rb]: I agree :-) I also think we should use "scheme" instead of "protocol", I can fix both tomorrow

Comment (dentarg) [reply spec/lib/twingly/url_spec.rb]: Hmm, after I've looked more closely I think it is a bigger task to use the style you suggest, because there's soo many specs that should be changed. I think if we start mixing, it might make the situation worse.

Comment (walro) [reply spec/lib/twingly/url_spec.rb]: I think the style I suggested is very prominent in the file? Are we thinking about the same thing?

Comment (walro) [reply spec/lib/twingly/url_spec.rb]: For example: https://github.com/twingly/twingly-url/blob/c2218e98ff0892e63adc483f4cf1c06e4f01f3ae/spec/lib/twingly/url_spec.rb#L102-L156 is in that style

I think the other style has snuck in lately

Comment (dentarg) [reply spec/lib/twingly/url_spec.rb]: I gave it a go anyway, but only for the new spec

Comment (walro) [reply spec/lib/twingly/url_spec.rb]: Ah, I see your change now.

**Comment by walro** [comment]
> Something changed, but I don't think it is particular breaking.

I don't know honestly. But seeing we're **probably** the only ones on version 6 I think we can go with 6.1 or even 6.0.1 here if we decide the previous behavior was a bug :)

**Comment by dentarg** [comment]
We have always downcases the scheme when normalizing, and I would argue that is in that situation it matters, when you want to compare URLs. Not sure what more one can do with URLs, other than "use" them, e.g. connect to them, and that should still work. That's my reasoning at least. :)

**Comment by walro** [comment]
Sounds reasonable.
