### PR TITLE
Fix "#valid? doesn't work for protocol-less urls"

### LINKED ISSUE #55: #valid? doesn't work for protocol-less urls
```ruby
irb(main):001:0> Twingly::URL.parse("//www.url.com")
=> #<Twingly::URL:0x3fd8a893c950 //www.url.com>
irb(main):002:0> Twingly::URL.parse("//www.url.com").valid?
NoMethodError: undefined method `downcase' for nil:NilClass
	from /Users/robin/Workspace/git/twingly-url/lib/twingly/url.rb:103:in `normalized_scheme'
	from /Users/robin/Workspace/git/twingly-url/lib/twingly/url.rb:126:in `valid?'
	from (irb):2
	from /Users/robin/.gem/ruby/2.2.3/gems/bundler-1.10.6/lib/bundler/cli/console.rb:14:in `run'
	from /Users/robin/.gem/ruby/2.2.3/gems/bundler-1.10.6/lib/bundler/cli.rb:308:in `console'
	from /Users/robin/.gem/ruby/2.2.3/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/robin/.gem/ruby/2.2.3/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/robin/.gem/ruby/2.2.3/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
	from /Users/robin/.gem/ruby/2.2.3/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
	from /Users/robin/.gem/ruby/2.2.3/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
	from /Users/robin/.gem/ruby/2.2.3/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
	from /Users/robin/.gem/ruby/2.2.3/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
	from /Users/robin/.gem/ruby/2.2.3/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
	from /Users/robin/.gem/ruby/2.2.3/bin/bundle:23:in `load'
	from /Users/robin/.gem/ruby/2.2.3/bin/bundle:23:in `<main>'
```

I think we can just switch the order of our if statements

Edit: or not, we need to do something else :)

### PR DESCRIPTION
**Pull request by walro**
There were lots of options to go with there:

* nil check in #scheme or #normalized_scheme
* .to_s in #scheme or #normalized_scheme
* use Addressable’s #normalized_scheme

I don’t think nil checks are that pretty, so that one was quickly discarded. I also don’t think we should #to_s “randomly” for some properties it’s either all or nothing in my opinion. Using Addressable’s own #normalized_scheme was the top candidate, but it did additional things to the url (not just downcasing it) and I think it’s a good thing that we try to control what we can when it comes to normalization.

So ultimately I went with this, I changed so that we check against #scheme instead of #normalized_scheme as that makes a whole lot of sense to me at least.

Fix #55.

Additionally, I did some refactoring which I felt was related to fixing this issue.

### CODE REVIEW

**Comment by dentarg** [comment]
I did this change

```diff
$ git d
diff --git a/spec/lib/twingly/url_spec.rb b/spec/lib/twingly/url_spec.rb
index e8cccdc..7eab2b2 100644
--- a/spec/lib/twingly/url_spec.rb
+++ b/spec/lib/twingly/url_spec.rb
@@ -37,7 +37,7 @@ end

 describe Twingly::URL do
   let(:test_url) do
-    "http://www.blog.twingly.co.uk/2015/07/01/language-detection-changes/"
+    "//www.blog.twingly.co.uk/2015/07/01/language-detection-changes/"
   end
   let(:url) { described_class.parse(test_url) }
```

And I got this result:

```rspec
Failures:

  1) Twingly::URL#scheme should eq "http"
     Failure/Error: it { is_expected.to eq("http") }

       expected: "http"
            got: nil

       (compared using ==)
     # ./spec/lib/twingly/url_spec.rb:132:in `block (3 levels) in <top (required)>'

  2) Twingly::URL#origin should eq "http://www.blog.twingly.co.uk"
     Failure/Error: it { is_expected.to eq("http://www.blog.twingly.co.uk") }

       expected: "http://www.blog.twingly.co.uk"
            got: "null"

       (compared using ==)
     # ./spec/lib/twingly/url_spec.rb:162:in `block (3 levels) in <top (required)>'

  3) Twingly::URL#normalized_scheme
     Failure/Error: subject { url.normalized_scheme }
     NoMethodError:
       undefined method `downcase' for nil:NilClass
     # ./lib/twingly/url.rb:107:in `normalized_scheme'
     # ./spec/lib/twingly/url_spec.rb:176:in `block (3 levels) in <top (required)>'
     # ./spec/lib/twingly/url_spec.rb:177:in `block (3 levels) in <top (required)>'
```

As you said, this may not be the place to fix 1), maybe that's business for #52.

I have no idea what's going on with 2) :smile: 

3) I think we need to address now.

File: lib/twingly/url.rb [hunk 1]
```diff
@@ -123,7 +127,7 @@ def normalized_path
     end
 
     def valid?
-      addressable_uri && public_suffix_domain && SCHEMES.include?(normalized_scheme)
+      !!(scheme =~ ACCEPTED_SCHEMES)
```
Comment (dentarg) [inline lib/twingly/url.rb]: It looks funny, seems like we only require a scheme to be valid, but I now that's not the case (this is the same as before). But I just wanted to write something about it.

I think making what we consider being an valid URL even more clear would be great. That might be future tasks for @twingly-mob.

**Comment by walro** [comment]
> 1), maybe that's business for #52.

Yes, I was thinking of that one.

> I have no idea what's going on with 2)

Haha, me neither. Probably somethnig we should fix.

> 3) I think we need to address now.

Hm, maybe here or maybe not. You really found a new problem (you effectively try to normalize an invalid url, not sure how it should work) :). The intended scope here was to ensure that "#valid?" does not lie to us. I think that #52 will solve this issue for us. Alternatively add another issue for "normalizing invalid urls behavior".

**Comment by dentarg** [comment]
Maybe all invalid URLs should return NullURL? But yeah, sounds like we need to have a new discussion elsewhere (not this issue/PR).

File: lib/twingly/url.rb (hunk 1 above)
Comment (walro) [inline lib/twingly/url.rb]: > It looks funny, seems like we only require a scheme to be valid, but I know that's not the case (this is the same as before). But I just wanted to write something about it.

My first attempt was actually this method returning `true` and I took care of this in `.internal_parse`, but then I realized that calling `#new` could lead to weird stuff (at least how it's currently implemented) so I went with the least amount of changes.

**Comment by walro** [comment]
> Maybe all invalid URLs should return NullURL? But yeah, sounds like we need to have a new discussion elsewhere (not this issue/PR).

Hehe, my thoughts exactly, just added that in https://github.com/twingly/twingly-url/pull/58#discussion_r43540632 :)

**Comment by twingly-mob** [comment]
Just a note about the "diff test" above

```diff
$ git d
diff --git a/spec/lib/twingly/url_spec.rb b/spec/lib/twingly/url_spec.rb
index 8fd4c7c..3cad381 100644
--- a/spec/lib/twingly/url_spec.rb
+++ b/spec/lib/twingly/url_spec.rb
@@ -37,7 +37,7 @@ end

 describe Twingly::URL do
   let(:test_url) do
-    "http://www.blog.twingly.co.uk/2015/07/01/language-detection-changes/"
+    "//www.blog.twingly.co.uk/2015/07/01/language-detection-changes/"
   end
   let(:url) { described_class.parse(test_url) }
```

Now the failures are as expected:

```
Failures:

  1) Twingly::URL#domain should eq "twingly.co.uk"
     Failure/Error: it { is_expected.to eq("twingly.co.uk") }

       expected: "twingly.co.uk"
            got: ""

       (compared using ==)
     # ./spec/lib/twingly/url_spec.rb:146:in `block (3 levels) in <top (required)>'

  2) Twingly::URL#normalized_path should eq "/2015/07/01/language-detection-changes"
     Failure/Error: it { is_expected.to eq("/2015/07/01/language-detection-changes") }

       expected: "/2015/07/01/language-detection-changes"
            got: ""

       (compared using ==)
     # ./spec/lib/twingly/url_spec.rb:166:in `block (3 levels) in <top (required)>'

  3) Twingly::URL#host should eq "www.blog.twingly.co.uk"
     Failure/Error: it { is_expected.to eq("www.blog.twingly.co.uk") }

       expected: "www.blog.twingly.co.uk"
            got: ""

       (compared using ==)
     # ./spec/lib/twingly/url_spec.rb:151:in `block (3 levels) in <top (required)>'

  4) Twingly::URL#origin should eq "http://www.blog.twingly.co.uk"
     Failure/Error: it { is_expected.to eq("http://www.blog.twingly.co.uk") }

       expected: "http://www.blog.twingly.co.uk"
            got: ""

       (compared using ==)
     # ./spec/lib/twingly/url_spec.rb:156:in `block (3 levels) in <top (required)>'

  5) Twingly::URL#normalized_scheme should eq "http"
     Failure/Error: it { is_expected.to eq("http") }

       expected: "http"
            got: ""

       (compared using ==)
     # ./spec/lib/twingly/url_spec.rb:171:in `block (3 levels) in <top (required)>'

  6) Twingly::URL#trd should eq "www.blog"
     Failure/Error: it { is_expected.to eq("www.blog") }

       expected: "www.blog"
            got: ""

       (compared using ==)
     # ./spec/lib/twingly/url_spec.rb:131:in `block (3 levels) in <top (required)>'

  7) Twingly::URL#sld should eq "twingly"
     Failure/Error: it { is_expected.to eq("twingly") }

       expected: "twingly"
            got: ""

       (compared using ==)
     # ./spec/lib/twingly/url_spec.rb:136:in `block (3 levels) in <top (required)>'

  8) Twingly::URL#normalized_host should eq "www.blog.twingly.co.uk"
     Failure/Error: it { is_expected.to eq("www.blog.twingly.co.uk") }

       expected: "www.blog.twingly.co.uk"
            got: ""

       (compared using ==)
     # ./spec/lib/twingly/url_spec.rb:176:in `block (3 levels) in <top (required)>'

  9) Twingly::URL#to_s should eq "//www.blog.twingly.co.uk/2015/07/01/language-detection-changes/"
     Failure/Error: it { is_expected.to eq(test_url) }

       expected: "//www.blog.twingly.co.uk/2015/07/01/language-detection-changes/"
            got: ""

       (compared using ==)
     # ./spec/lib/twingly/url_spec.rb:450:in `block (3 levels) in <top (required)>'

  10) Twingly::URL#scheme should eq "http"
      Failure/Error: it { is_expected.to eq("http") }

        expected: "http"
             got: ""

        (compared using ==)
      # ./spec/lib/twingly/url_spec.rb:126:in `block (3 levels) in <top (required)>'

  11) Twingly::URL.parse should be a kind of Twingly::URL
      Failure/Error: it { is_expected.to be_a(Twingly::URL) }
        expected #<Twingly::URL::NullURL:0x007fba4b56eb10> to be a kind of Twingly::URL
      # ./spec/lib/twingly/url_spec.rb:47:in `block (3 levels) in <top (required)>'

  12) Twingly::URL#tld should eq "co.uk"
      Failure/Error: it { is_expected.to eq("co.uk") }

        expected: "co.uk"
             got: ""

        (compared using ==)
      # ./spec/lib/twingly/url_spec.rb:141:in `block (3 levels) in <top (required)>'

  13) Twingly::URL#path should eq "/2015/07/01/language-detection-changes/"
      Failure/Error: it { is_expected.to eq("/2015/07/01/language-detection-changes/") }

        expected: "/2015/07/01/language-detection-changes/"
             got: ""

        (compared using ==)
      # ./spec/lib/twingly/url_spec.rb:161:in `block (3 levels) in <top (required)>'

Finished in 0.26022 seconds (files took 0.27812 seconds to load)
136 examples, 13 failures
```
